### ISSUE TITLE
turbulent_fluxes failure with CoupledAtmos

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#476]
## Describe the bug
When running the bucket model with a CoupledAtmosphere, turbulent_fluxes returns a `NamedTuple`. This is what ClimaCoupler was doing previously and isn't a bug itself, but this change was made at the same time that `update_aux` was changed to broadcast over `turbulent_fluxes` (see change [here](https://github.com/CliMA/ClimaLand.jl/compare/v0.6.0...v0.7.0#diff-da195e37edf7ac71968ff125c60ee4eef7886667488ff08b6ecef0618c904734L558-R569)). Broadcasting over NamedTuples isn't allowed, so this gives an error.

When the bucket is run with a PrescribedAtmosphere, `turbulent_fluxes` returns a field, which we can broadcast over, which is why we didn't catch this sooner. It would be nice to add a test that sets up the bucket with a CoupledAtmosphere and CoupledRadiativeFluxes and checks that everything can run smoothly.

failing buildkite run from coupler: https://buildkite.com/clima/climacoupler-ci/builds/2547

fixed by #479

**Comment by kmdeck** [comment]
oh, it's a question of a NamedTuple of fields vs a field of NamedTuples?

I think I made the change partially because I thought it would reduce allocations
before we had
```
https://github.com/CliMA/ClimaLand.jl/blob/4580daa527ba0eaccb6f3c1e7b4f61853cc7ab7f/src/standalone/Bucket/Bucket.jl#L557
```
which I thought allocated a Named Tuple of fields each step (we already have the fields `lhf` etc allocated but not using them in the return statement of `turbulent_fluxes`).

ideally we can modify the CoupledAtmos method of `turbulent_fluxes` appropriately. But i think `turbulent_fluxes` allocates within the function too, so there is optimization to be done there, and maybe things will change in the future.

**Comment by kmdeck** [comment]
for your other question: I think it is useful to store SHF and LHF separately. if collectively across clima we decide we dont need them both, land can change its variables, but otherwise maybe atmos can change to provide both in its computation, instead of just the sum. for now, in coupled runs, we can set SHF as the sum and LHF as zero.

**Comment by juliasloan25** [comment]
> oh, it's a question of a NamedTuple of fields vs a field of NamedTuples?

Yeah, I think that's right. The `update_aux` change makes sense to me, so the simplest change is probably to change `turbulent_fluxes` for the `CoupledAtmosphere` to return a field of tuples, like you said. I think we can come up with a way to repackage the tuple fields in the return [here](https://github.com/CliMA/ClimaLand.jl/compare/v0.6.0...v0.7.0#diff-a97492469e0d60da6ffa468219144b6c7187de8f93bdb8a8b7e7c5bfb3654379R334-R338) to a field of tuples

**Comment by juliasloan25** [comment]
We can actually just return `model_cache.turbulent_fluxes` instead of accessing each of the individual fields and creating a NamedTuple from them. I added a method doing this in ClimaCoupler ([here](https://github.com/CliMA/ClimaCoupler.jl/pull/598/files#diff-1a48ea887d5f076f8ee1d4e99f6e295f24cf74c13b35b7497a4a5fc623a7688cR48)) that works, but I'll remove it after we update ClimaLand
